server:
  port: 9003

spring:
  application:
    name: code-generator
  redis:
    host: 10.65.1.99
    port: 6379
    password:
    database: 0
    timeout: 60
    testOnBorrow: true
    jedis:
      pool:
        max-total: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    dynamic:
      primary: codeGenerator
      datasource:
        codeGenerator:
          url: jdbc:mysql://localhost:3306/code_generator?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          #com.mysql.cj.jdbc.Driver
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        #初始化时建立物理连接的个数
        initialSize: 1
        #池中最大连接数
        maxActive: 20
        #最小空闲连接
        minIdle: 1
        #获取连接时最大等待时间，单位毫秒
        maxWait: 60000
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates
#    mode: HTML
#    suffix: .html

## Mybatis 配置
mybatis-plus:
  check-config-location: true
  #指定xml映射位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger2:
  basePackage: com.alan.cloud.codegenerator
  version: 1.0.0
  title: L & P
  description: 贯彻爱与和平！

ignore:
  urls:
    - /css/**
    - /js/**
    - /img/**
    - /ued/**
    - /*.js
    - /*.css
    - /login
    - /**/*.css
    - /info
    - /health
    - /session
    - /druid